name: Rispondi a richiesta preventivo

on:
permissions:
  contents: write
  workflow_dispatch:

jobs:
  esempio:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow attivo!"
      - name: Commit e push risposta
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add risposte/risposta-preventivo.md
          git commit -m "Risposta generata da ChatGPT"
          git push
